org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=smartsiege
mod_name=Smart Siege
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.smartsiege.mod
mod_authors=You
mod_description=Gives hostile mobs smarter, more dangerous AI: they dig, break doors, dodge projectiles, avoid explosions, call for backup, and ambush the player.
